#!/bin/bash

cd $HADOOP_PREFIX

bin/hadoop fs -mkdir lordofthejars
bin/hadoop fs -ls lordofthejars 

bin/hadoop fs -put $HADOOP_PREFIX/input/Lab2-WC-Input.txt lordofthejars
bin/hadoop fs -ls lordofthejars

bin/hadoop jar WordCount.jar edu.miu.cs.cs523.WordCount lordofthejars output
bin/hadoop fs -ls output 

bin/hadoop fs -cat output/part-r-00000
